import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useApi } from "../ApiContext";
import type { VaultNote, VaultState } from "../api";
import { Button, Dialog, Input } from "./ui";

const empty:VaultNote={id:"decisions/",title:"",body:"",revision:0};
export function VaultButton({threadId,onMention}:{threadId:string;onMention?:(text:string)=>void}) {
  const [open,setOpen]=useState(false);
  return <><Button onClick={()=>setOpen(true)}>Project memory</Button>{open&&<Vault threadId={threadId} onClose={()=>setOpen(false)} onMention={onMention}/>}</>;
}
function Vault({threadId,onClose,onMention}:{threadId:string;onClose:()=>void;onMention?: (text:string)=>void}) {
  const api=useApi(),qc=useQueryClient();
  const key=["vault",threadId];
  const query=useQuery({queryKey:key,queryFn:()=>api.vault(threadId)});
  const [selected,setSelected]=useState("");
  const [search,setSearch]=useState("");
  const [view,setView]=useState<"notes"|"graph"|"proposals"|"learning">("notes");
  const [draft,setDraft]=useState<VaultNote|null>(null);
  const [discard,setDiscard]=useState(false);
  const save=useMutation({mutationFn:(note:VaultNote)=>api.saveNote(threadId,note,note.revision),onSuccess:n=>{setDraft(null);setDiscard(false);setSelected(n.id);qc.invalidateQueries({queryKey:key});}});
  const resolve=useMutation({mutationFn:({id,accepted}:{id:string;accepted:boolean})=>api.resolveNote(threadId,id,accepted),onSuccess:()=>qc.invalidateQueries({queryKey:key})});
  const rebuild=useMutation({mutationFn:()=>api.rebuildVault(threadId)});
  const notes=query.data?.notes??[];
  const note=notes.find(n=>n.id===selected);
  const filtered=notes.filter(n=>`${n.id} ${n.title} ${n.body}`.toLowerCase().includes(search.toLowerCase()));
  const select=(id:string)=>{setSelected(id);setView("notes");};
  const error=query.error??save.error??resolve.error??rebuild.error;
  return <Dialog title="Project memory" variant="viewer" onClose={()=>draft?setDiscard(true):onClose()}>
    <p className="mb-3 text-[12px] text-dim">Approved project notes. Agents can propose decisions; only accepted notes enter memory. Notes are reference data, not instructions.</p>
    <nav className="mb-4 flex flex-wrap gap-2" aria-label="Memory views">{(["notes","graph","proposals","learning"] as const).map(v=><Button key={v} aria-pressed={view===v} disabled={!!draft} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}{v==="proposals"?` (${query.data?.proposals.length??0})`:""}</Button>)}<Button disabled={!!draft} onClick={()=>{setDraft({...empty});setView("notes");}}>New note</Button><Button disabled={rebuild.isPending} onClick={()=>rebuild.mutate()}>Rebuild Markdown files</Button></nav>
    {query.isPending&&<p role="status">Loading project memory…</p>}
    {error&&<div id="vault-note-error" role="alert" className="mb-3 text-bad">{error.message} <Button onClick={()=>query.refetch()}>Reload notes</Button></div>}
    {rebuild.isSuccess&&<p role="status" className="text-ok">Markdown files rebuilt from approved notes.</p>}
    {discard&&<div role="alert" className="mb-3 rounded border border-warn p-3">Discard unsaved note edits?<div className="mt-2 flex gap-2"><Button autoFocus onClick={()=>setDiscard(false)}>Keep editing</Button><Button onClick={()=>{setDraft(null);setDiscard(false);onClose();}}>Discard edits and close</Button></div></div>}
    {draft ? <form noValidate className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate(draft);}}>
      <label className="block">Note ID<Input aria-invalid={!!save.error} aria-describedby={save.error?"vault-note-error":undefined} disabled={draft.revision>0} value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value})}/><span className="text-[12px] text-dim">Category/slug, using lowercase letters, digits and hyphens. Categories: plans, tasks, decisions, handoffs, learnings, files.</span></label>
      <label className="block">Title<Input aria-invalid={!!save.error} aria-describedby={save.error?"vault-note-error":undefined} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
      <label className="block">Markdown<textarea aria-invalid={!!save.error} aria-describedby={save.error?"vault-note-error":undefined} className="mt-1 min-h-48 w-full resize-none rounded border border-line bg-bg p-3 font-mono" rows={10} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label>
      <p className="text-[12px] text-dim">Link notes with [[category/slug]]. Secrets and instruction-like text are rejected. Saving approves this note for project memory.</p>
      <div className="sticky bottom-0 flex gap-2 border-t border-line bg-panel py-3"><Button type="submit" variant="primary" disabled={save.isPending}>Save approved note</Button><Button type="button" disabled={save.isPending} onClick={()=>setDiscard(true)}>Cancel edits</Button></div>
    </form> : view==="learning" ? <Learning threadId={threadId}/> : view==="graph" ? <NoteGraph data={query.data} onSelect={select}/> : view==="proposals" ? <div className="space-y-4">
      {!query.data?.proposals.length&&<p className="text-dim">No decisions awaiting review.</p>}
      {query.data?.proposals.map(p=><article key={p.id} className="rounded border border-line p-3"><h3 className="font-semibold">{p.note.title}</h3><p className="break-all text-[12px] text-dim">{p.note.id} · based on revision {p.base_revision}</p><div className="my-3 grid gap-3 lg:grid-cols-2"><div><h4>Current approved note</h4><pre className="mt-2 whitespace-pre-wrap break-words rounded bg-bg p-3 text-[12px]">{notes.find(n=>n.id===p.note.id)?.body??"New note"}</pre></div><div><h4>Proposed replacement</h4><pre className="mt-2 whitespace-pre-wrap break-words rounded border border-accent/30 bg-bg p-3 text-[12px]">{p.note.body}</pre></div></div><div className="flex gap-2"><Button variant="primary" disabled={resolve.isPending} onClick={()=>resolve.mutate({id:p.id,accepted:true})}>Accept decision</Button><Button disabled={resolve.isPending} onClick={()=>resolve.mutate({id:p.id,accepted:false})}>Reject</Button></div></article>)}
    </div> : <div className="grid min-w-0 gap-4 lg:grid-cols-[18rem_minmax(0,1fr)]"><aside><div className="mb-3 flex gap-2"><Input aria-label="Search notes" placeholder="Search notes" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<Button onClick={()=>setSearch("")}>Clear</Button>}</div><ul className="max-h-64 space-y-1 overflow-auto lg:max-h-[55dvh]">{filtered.map(n=><li key={n.id}><button className={`w-full break-words rounded p-2 text-left hover:bg-raised ${selected===n.id?"bg-raised":""}`} onClick={()=>select(n.id)}>{n.title}<span className="block break-all text-[12px] text-dim">{n.id}</span></button></li>)}</ul>{!filtered.length&&<p className="text-dim">{notes.length?"No matching notes.":"No approved notes yet. Plans and handoffs create notes automatically."}</p>}</aside><article className="min-w-0">{note?<><div className="flex flex-wrap gap-2"><h3 className="min-w-0 flex-1 break-words text-lg font-semibold">{note.title}</h3><Button onClick={()=>setDraft({...note})}>Edit note</Button>{onMention&&<Button onClick={()=>{onMention(`[[${note.id}]]`);onClose();}}>Mention in message</Button>}</div><p className="mt-1 break-all text-[12px] text-dim">{note.id} · revision {note.revision}</p><pre className="my-4 whitespace-pre-wrap break-words font-sans leading-relaxed">{note.body}</pre><h4 className="font-semibold">Links</h4><div className="my-2 flex flex-wrap gap-2">{query.data?.links.filter(l=>l.from===note.id).map(l=><Button key={l.to} disabled={!notes.some(n=>n.id===l.to)} onClick={()=>select(l.to)}>{l.to}{!notes.some(n=>n.id===l.to)?" (missing)":""}</Button>)}</div><h4 className="font-semibold">Backlinks</h4><div className="mt-2 flex flex-wrap gap-2">{query.data?.links.filter(l=>l.to===note.id).map(l=><Button key={l.from} onClick={()=>select(l.from)}>{l.from}</Button>)}</div></>:<p className="text-dim">Choose a note to read its content and backlinks.</p>}</article></div>}
  </Dialog>;
}

function NoteGraph({data,onSelect}:{data?:VaultState;onSelect:(id:string)=>void}) {
  const notes=data?.notes.slice(0,50)??[];
  const point=(id:string)=>{const i=notes.findIndex(n=>n.id===id);return i<0?null:{x:30+(i%3)*260,y:35+Math.floor(i/3)*100};};
  return <><p className="mb-3 text-[12px] text-dim">Links between the first 50 notes. Select a note to read it. Scroll within the graph to explore.</p>{!notes.length?<p className="text-dim">The graph appears when notes are added.</p>:<div tabIndex={0} aria-label="Note graph; scroll to explore" className="max-h-[60dvh] overflow-auto rounded border border-line"><svg width="810" height={Math.max(140,Math.ceil(notes.length/3)*100+40)} role="group" aria-label="Linked project notes">{data?.links.map(l=>{const a=point(l.from),b=point(l.to);return a&&b?<line key={`${l.from}-${l.to}`} x1={a.x+115} y1={a.y+28} x2={b.x+115} y2={b.y+28} stroke="currentColor" className="text-faint"/>:null;})}{notes.map(n=>{const p=point(n.id)!;return <g key={n.id} role="button" tabIndex={0} aria-label={`Open ${n.title}`} onClick={()=>onSelect(n.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(n.id);}}} className="cursor-pointer text-fg"><rect x={p.x} y={p.y} width="230" height="56" rx="6" className="fill-panel stroke-accent"/><text x={p.x+10} y={p.y+23} fill="currentColor" fontSize="13">{n.title.slice(0,29)}</text><text x={p.x+10} y={p.y+43} fill="currentColor" fontSize="11">{n.id.slice(0,34)}</text><title>{n.title} — {n.id}</title></g>;})}</svg></div>}</>;
}

function Learning({threadId}:{threadId:string}) {
  const api=useApi(),qc=useQueryClient();
  const key=["learning",threadId];
  const query=useQuery({queryKey:key,queryFn:()=>api.learning(threadId)});
  const [kind,setKind]=useState("feature"),[choice,setChoice]=useState("auto"),[model,setModel]=useState("");
  const save=useMutation({mutationFn:()=>api.routingPreference(threadId,kind,["auto","disabled"].includes(choice)?null:choice,model.trim()||null,choice!=="disabled"),onSuccess:()=>qc.invalidateQueries({queryKey:key})});
  const rework=useMutation({mutationFn:({id,value}:{id:string;value:boolean})=>api.markRework(id,value),onSuccess:()=>qc.invalidateQueries({queryKey:key})});
  return <section><p className="mb-4 text-[12px] text-dim">Measured check outcomes per task. Automatic routing needs at least three outcomes for a model and task type. Tasks without configured checks are excluded from scores. Explicit model choices take priority. Token counts come from the harness; zero may mean no usage was reported.</p>{query.isPending&&<p role="status">Loading outcomes…</p>}{(query.error||save.error||rework.error)&&<p role="alert" className="text-bad">{(query.error||save.error||rework.error)?.message} <Button onClick={()=>query.refetch()}>Retry</Button></p>}<div className="overflow-auto"><table className="w-full text-left text-[12px]"><thead><tr>{["Task type","Harness / model","First try","Passed","Rework","Tokens","Cost"].map(h=><th key={h} className="border-b border-line p-2">{h}</th>)}</tr></thead><tbody>{query.data?.strengths.map(s=><tr key={`${s.task_type}-${s.harness}-${s.model}`}><td className="p-2">{s.task_type}</td><td className="p-2">{s.harness} / {s.model??"default (unreported model)"}</td><td className="p-2">{s.first_try}/{s.runs}</td><td className="p-2">{s.passed}/{s.runs}</td><td className="p-2">{s.rework}</td><td className="p-2">{s.tokens.toLocaleString()}</td><td className="p-2">${s.cost_usd.toFixed(4)}</td></tr>)}</tbody></table></div>{query.data?.strengths.length===0&&<p className="my-3 text-dim">No check outcomes recorded yet.</p>}
    <form noValidate className="my-5 flex flex-wrap items-end gap-3 rounded border border-line p-3" onSubmit={e=>{e.preventDefault();save.mutate();}}><label>Task type<select className="ml-2 rounded border border-line bg-bg p-2" value={kind} onChange={e=>setKind(e.target.value)}>{["feature","bugfix","refactor","test","docs","ops","research"].map(k=><option key={k} value={k}>{k}</option>)}</select></label><label>Routing<select aria-label="Routing preference" className="ml-2 rounded border border-line bg-bg p-2" value={choice} onChange={e=>setChoice(e.target.value)}><option value="auto">Learn from outcomes</option><option value="disabled">Use availability and load</option><option value="claude">Prefer Claude</option><option value="codex">Prefer Codex</option></select></label>{["claude","codex"].includes(choice)&&<label>Model ID (optional)<Input value={model} onChange={e=>setModel(e.target.value)}/></label>}<Button type="submit" disabled={save.isPending||!kind.trim()}>Save routing preference</Button></form>{save.isSuccess&&<p role="status" className="text-ok">Routing preference saved for future automatic assignments.</p>}
    <h3 className="font-semibold">Saved preferences</h3><ul className="my-2">{Object.entries(query.data?.preferences??{}).map(([k,p])=><li key={k}>{k}: {p.enabled?p.harness??"learned routing":"availability and load"}{p.model?` / ${p.model}`:""} <Button onClick={()=>{setKind(k);setChoice(p.enabled?p.harness??"auto":"disabled");setModel(p.model??"");}}>Edit</Button></li>)}</ul><h3 className="mt-4 font-semibold">User rework</h3><p className="text-[12px] text-dim">Mark tasks whose result needed manual correction. This reduces their routing score.</p><ul className="mt-2 space-y-2">{Object.entries(query.data?.outcomes??{}).map(([id,o])=><li key={id}><label className="flex items-start gap-2"><input type="checkbox" disabled={rework.isPending} checked={o.user_rework} onChange={e=>rework.mutate({id,value:e.target.checked})}/><span className="break-all text-[12px]">{id} · {o.task_type} · {o.harness} · {o.checks_run===0?"no acceptance checks":o.passed?"passed":"failed"} · {o.heal_attempts} heal attempts</span></label></li>)}</ul>
  </section>;
}
